import type {
  AlertItem,
  ConnectedSource,
  EmailEvent,
  EvidenceItem,
  Investigation,
  Machine,
} from "@/types";

export const TARGET_MACHINE = "M-37";

export const MACHINES: Machine[] = [
  {
    id: "M-12",
    name: "Hydraulic Press #12",
    kind: "Press",
    line: "Line A",
    mission: "Mission A — Chassis",
    baseline: { output: 148, cycleTime: 24.2, vibration: 2.1, temperature: 58, power: 31 },
    installed: "2019-04-11",
    lastService: "2026-07-02",
  },
  {
    id: "M-19",
    name: "CNC Mill #19",
    kind: "CNC",
    line: "Line A",
    mission: "Mission A — Chassis",
    baseline: { output: 96, cycleTime: 37.4, vibration: 1.6, temperature: 49, power: 22 },
    installed: "2020-09-23",
    lastService: "2026-06-18",
  },
  {
    id: "M-24",
    name: "Robotic Welder #24",
    kind: "Welder",
    line: "Line B",
    mission: "Mission B — Drivetrain",
    baseline: { output: 132, cycleTime: 27.1, vibration: 2.4, temperature: 71, power: 44 },
    installed: "2018-02-04",
    lastService: "2026-08-01",
  },
  {
    id: "M-31",
    name: "Injection Molder #31",
    kind: "Molder",
    line: "Line B",
    mission: "Mission B — Drivetrain",
    baseline: { output: 118, cycleTime: 30.5, vibration: 1.9, temperature: 84, power: 52 },
    installed: "2021-01-19",
    lastService: "2026-05-27",
  },
  {
    id: "M-37",
    name: "Pick & Place Arm #37",
    kind: "Robotic Arm",
    line: "Line B",
    mission: "Mission B — Drivetrain",
    baseline: { output: 124, cycleTime: 29.0, vibration: 2.2, temperature: 62, power: 28 },
    installed: "2017-11-30",
    lastService: "2026-03-14",
  },
  {
    id: "M-44",
    name: "Packaging Cell #44",
    kind: "Packaging",
    line: "Line C",
    mission: "Mission C — Finishing",
    baseline: { output: 210, cycleTime: 17.2, vibration: 1.2, temperature: 41, power: 18 },
    installed: "2022-06-08",
    lastService: "2026-07-29",
  },
];

export const CONNECTED_SOURCES: ConnectedSource[] = [
  { id: "src-1", name: "Ceiling CCTV — Bay 4", type: "Vision", status: "streaming", latencyMs: 180 },
  { id: "src-2", name: "Gripper CCTV", type: "Vision", status: "streaming", latencyMs: 210 },
  { id: "src-3", name: "Triaxial Vibration Sensor", type: "Sensor", status: "degraded", latencyMs: 60 },
  { id: "src-4", name: "Bearing Temp Probe", type: "Sensor", status: "streaming", latencyMs: 55 },
  { id: "src-5", name: "Servo Current Monitor", type: "Sensor", status: "streaming", latencyMs: 48 },
  { id: "src-6", name: "PLC Cycle Counter", type: "Controller", status: "streaming", latencyMs: 32 },
  { id: "src-7", name: "MES Production Feed", type: "System", status: "streaming", latencyMs: 420 },
  { id: "src-8", name: "SCADA Historian", type: "System", status: "streaming", latencyMs: 380 },
  { id: "src-9", name: "Quality Inspection Camera", type: "Vision", status: "streaming", latencyMs: 260 },
  { id: "src-10", name: "Maintenance Log (CMMS)", type: "Document", status: "streaming", latencyMs: 640 },
  { id: "src-11", name: "OEM Service Manual Index", type: "Document", status: "streaming", latencyMs: 710 },
  { id: "src-12", name: "Shift Handover Notes", type: "Document", status: "streaming", latencyMs: 520 },
  { id: "src-13", name: "Energy Submeter B-2", type: "Sensor", status: "offline", latencyMs: 0 },
];

export const EVIDENCE: EvidenceItem[] = [
  {
    id: "ev-1",
    source: "Vibration Sensor",
    summary: "Axis-2 RMS climbed from 2.2 to 5.1 mm/s over 6 hours — harmonic at 148 Hz matches bearing outer race.",
    weight: 0.31,
    captured: "06:12",
  },
  {
    id: "ev-2",
    source: "Gripper CCTV",
    summary: "Frame analysis shows 40 mm overshoot on pick approach, corrected by a secondary micro-move on 61% of cycles.",
    weight: 0.24,
    captured: "07:48",
  },
  {
    id: "ev-3",
    source: "PLC Cycle Counter",
    summary: "Median cycle time increased 29.0 s → 33.6 s; retry counter incremented 214 times this shift.",
    weight: 0.19,
    captured: "08:05",
  },
  {
    id: "ev-4",
    source: "Maintenance Log",
    summary: "Axis-2 harmonic drive last greased 2026-03-14 — 158 days, exceeds the 120-day OEM interval.",
    weight: 0.15,
    captured: "08:11",
  },
  {
    id: "ev-5",
    source: "Servo Current Monitor",
    summary: "Peak servo current up 18% at identical payload, consistent with increased mechanical drag.",
    weight: 0.11,
    captured: "08:19",
  },
];

export const SEED_ALERTS: AlertItem[] = [
  {
    id: "AL-1041",
    title: "Production output down 9.8% on Mission B",
    detail: "Line B throughput fell below the shift floor of 118 u/hr for 42 consecutive minutes.",
    severity: "critical",
    mission: "Mission B — Drivetrain",
    confidence: 0.92,
    signals: ["MES Production Feed", "PLC Cycle Counter"],
    createdAt: "08:22",
    status: "Open",
  },
  {
    id: "AL-1042",
    title: "Vibration anomaly on Pick & Place Arm #37",
    detail: "Axis-2 RMS vibration exceeded 4.0 mm/s with a rising trend and bearing-race harmonic signature.",
    severity: "warning",
    machineId: "M-37",
    mission: "Mission B — Drivetrain",
    confidence: 0.88,
    signals: ["Triaxial Vibration Sensor", "Servo Current Monitor"],
    createdAt: "07:54",
    status: "Open",
  },
  {
    id: "AL-1043",
    title: "Cycle time drift on Pick & Place Arm #37",
    detail: "Median cycle time drifted +15.9% against the 30-day baseline.",
    severity: "warning",
    machineId: "M-37",
    mission: "Mission B — Drivetrain",
    confidence: 0.81,
    signals: ["PLC Cycle Counter", "SCADA Historian"],
    createdAt: "07:31",
    status: "Acknowledged",
  },
  {
    id: "AL-1044",
    title: "Cross-sense correlation: vision + vibration + throughput",
    detail: "Three independent modalities point to the same asset within a 90-minute window.",
    severity: "critical",
    machineId: "M-37",
    mission: "Mission B — Drivetrain",
    confidence: 0.84,
    signals: ["Gripper CCTV", "Triaxial Vibration Sensor", "MES Production Feed"],
    createdAt: "08:25",
    status: "Investigating",
  },
];

export const INVESTIGATIONS: Investigation[] = [
  {
    id: "INV-204",
    title: "Root cause: Mission B throughput loss",
    machineId: "M-37",
    trigger: "AL-1041 — Production output down 9.8%",
    confidence: 0.84,
    cost: 0.42,
    status: "Awaiting Approval",
    conclusion:
      "Pick & Place Arm #37 is the most likely source of the Mission B throughput loss. Axis-2 harmonic drive wear is producing vibration, positional overshoot and retry cycles that add ~4.6 s per part downstream.",
    recommendation:
      "Schedule a 45-minute maintenance window this shift: re-grease and inspect the Axis-2 harmonic drive, re-run the gripper calibration routine, then verify with a 30-cycle test run.",
    steps: [
      {
        id: "st-1",
        agent: "Vision Agent",
        role: "Reads camera feeds for motion and defect anomalies",
        tools: ["Gripper CCTV", "Bay 4 CCTV", "Frame diff"],
        finding: "Detected repeated 40 mm overshoot and corrective micro-moves on 61% of pick cycles.",
        confidence: 0.79,
        cost: 0.11,
      },
      {
        id: "st-2",
        agent: "Sensor Agent",
        role: "Analyses vibration, temperature and current streams",
        tools: ["Vibration sensor", "FFT", "Servo current"],
        finding: "148 Hz harmonic matches the Axis-2 bearing outer race; RMS up 132% since 02:00.",
        confidence: 0.91,
        cost: 0.08,
      },
      {
        id: "st-3",
        agent: "Data Agent",
        role: "Correlates production data against asset behaviour",
        tools: ["MES feed", "SCADA historian", "SQL"],
        finding: "Line B loss of 9.8% aligns 1:1 with #37 retry events; other assets are within baseline.",
        confidence: 0.87,
        cost: 0.09,
      },
      {
        id: "st-4",
        agent: "Document Agent",
        role: "Searches manuals, logs and handover notes",
        tools: ["CMMS", "OEM manual index", "Shift notes"],
        finding: "Axis-2 grease interval exceeded by 38 days; OEM flags this exact failure signature.",
        confidence: 0.74,
        cost: 0.06,
      },
      {
        id: "st-5",
        agent: "Computer Agent",
        role: "Prepares work orders and notifications",
        tools: ["CMMS write", "Email composer"],
        finding: "Drafted work order WO-8871 and technician notification pending human approval.",
        confidence: 0.95,
        cost: 0.04,
      },
      {
        id: "st-6",
        agent: "Verification Agent",
        role: "Cross-checks findings and rules out alternatives",
        tools: ["Consistency check", "Counterfactual"],
        finding: "Ruled out material supply and Welder #24; no competing hypothesis above 12% likelihood.",
        confidence: 0.84,
        cost: 0.04,
      },
    ],
  },
  {
    id: "INV-203",
    title: "Energy submeter B-2 dropout",
    machineId: "M-31",
    trigger: "Source health monitor",
    confidence: 0.68,
    cost: 0.12,
    status: "Approved",
    conclusion: "Submeter B-2 lost its gateway link; no production impact detected.",
    recommendation: "Network team to power-cycle the B-2 gateway at next changeover.",
    steps: [],
  },
];

export const SEED_EMAILS: EmailEvent[] = [
  {
    id: "EM-1",
    subject: "[Cross-Sense] Mission B output down 9.8% — investigation started",
    from: "crosssense-ai@plant.local",
    to: "ops-supervisor@plant.local",
    stage: "Alert",
    status: "Sent",
    sentAt: "08:22",
    body: "Automated detection: Line B throughput fell below the shift floor. A multi-agent investigation (INV-204) has been started across vision, sensor, data and document sources.",
  },
  {
    id: "EM-2",
    subject: "[Cross-Sense] Approval needed — maintenance on {{machine}}",
    from: "crosssense-ai@plant.local",
    to: "plant-manager@plant.local",
    stage: "Approval",
    status: "Queued",
    sentAt: "08:31",
    body: "Investigation INV-204 concluded with {{confidence}} confidence that {{machine}} is the source. Current vibration is {{vibration}} mm/s and cycle time {{cycle}} s. Requesting approval for a 45-minute maintenance window.",
  },
  {
    id: "EM-3",
    subject: "[Cross-Sense] Work order WO-8871 assigned — Axis-2 harmonic drive",
    from: "cmms@plant.local",
    to: "tech.rivera@plant.local",
    stage: "Worker",
    status: "Draft",
    sentAt: "08:36",
    body: "Task: re-grease and inspect the Axis-2 harmonic drive on {{machine}}, re-run gripper calibration, verify with a 30-cycle test. Evidence pack attached (5 items).",
  },
  {
    id: "EM-4",
    subject: "[Cross-Sense] Work order WO-8871 completed",
    from: "tech.rivera@plant.local",
    to: "ops-supervisor@plant.local",
    stage: "Completion",
    status: "Draft",
    sentAt: "09:24",
    body: "Harmonic drive re-greased, worn seal replaced, calibration re-run. Machine returned to production at 09:22.",
  },
  {
    id: "EM-5",
    subject: "[Cross-Sense] Recovery verified — Mission B back to baseline",
    from: "crosssense-ai@plant.local",
    to: "plant-manager@plant.local",
    stage: "Verification",
    status: "Draft",
    sentAt: "09:41",
    body: "Post-fix verification: {{machine}} vibration {{vibration}} mm/s, cycle time {{cycle}} s, output {{output}} u/hr. Mission B throughput recovered. Estimated loss avoided: {{savings}}.",
  },
];
